packages:
  - name: cloud
    actions:
      - name: getCoffee
        limits:
          timeout: 5000
          memory: 256
      - name: postEmail
        limits:
          timeout: 5000
          memory: 256
environment:
  DB_URL: ${DB_URL}
